import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Linking,Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import MapView,{Marker,Polyline} from 'react-native-maps';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {searchAddress,searchPlace,type GeocodingResult} from './services/geocoding';
import {importAddressesFromImage,normalizeAddress} from './services/addressImport';
import {openRouteInOsmAnd} from './services/osmand';
import {shareRouteAsGpx} from './services/shareGpx';
import {clearSearchArea,loadSearchArea,saveSearchArea,type SearchArea} from './services/searchArea';
import type {RoutePoint} from './types/route';

const FALLBACK={latitude:59.3293,longitude:18.0686,latitudeDelta:8,longitudeDelta:8};
const RADII=[1,5,10,25,50,100];

export default function RouteMapperScreen(){
 const insets=useSafeAreaInsets(),map=useRef<MapView>(null);
 const [points,setPoints]=useState<RoutePoint[]>([]); const [sat,setSat]=useState(true); const [query,setQuery]=useState(''); const [results,setResults]=useState<GeocodingResult[]>([]); const [searchOpen,setSearchOpen]=useState(false); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
 const [area,setArea]=useState<SearchArea|null>(null); const [areaOpen,setAreaOpen]=useState(false); const [areaQuery,setAreaQuery]=useState(''); const [areaResults,setAreaResults]=useState<GeocodingResult[]>([]); const [areaRadius,setAreaRadius]=useState(25);
 useEffect(()=>{loadSearchArea().then(a=>{setArea(a);if(a)setAreaRadius(a.radiusKm)}).catch(()=>{});},[]);
 const add=(r:{latitude:number;longitude:number},label?:string)=>setPoints(old=>{const k=`${r.latitude.toFixed(6)},${r.longitude.toFixed(6)}`;if(old.some(p=>`${p.latitude.toFixed(6)},${p.longitude.toFixed(6)}`===k||normalizeAddress(p.label||'')===normalizeAddress(label||'')))return old;return [...old,{id:`${Date.now()}-${old.length}`,latitude:r.latitude,longitude:r.longitude,label:label||`Stopp ${old.length+1}`}];});
 const search=async()=>{if(!query.trim())return;setBusy(true);setMsg('');try{setResults(await searchAddress(query));}catch(e){setMsg(e instanceof Error?e.message:'Adressökningen misslyckades.')}finally{setBusy(false)}};
 const importImage=async()=>{setBusy(true);try{const found=await importAddressesFromImage();let n=0;setPoints(old=>{const names=new Set(old.map(p=>normalizeAddress(p.label||''))),coords=new Set(old.map(p=>`${p.latitude.toFixed(6)},${p.longitude.toFixed(6)}`)),next=[...old];for(const r of found){const name=normalizeAddress(r.displayName),coord=`${r.latitude.toFixed(6)},${r.longitude.toFixed(6)}`;if(names.has(name)||coords.has(coord))continue;next.push({id:`${Date.now()}-${next.length}`,latitude:r.latitude,longitude:r.longitude,label:r.displayName.split(',').slice(0,2).join(', ')});names.add(name);coords.add(coord);n++;}return next});setMsg(`${n} nya adresser importerades.`)}catch{setMsg('Kunde inte läsa bilden.')}finally{setBusy(false)}};
 const street=async()=>{const p=points.at(-1);if(!p)return setMsg('Ingen position att visa.');try{await Linking.openURL(`https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${p.latitude},${p.longitude}`)}catch{setMsg('Kunde inte öppna Street View.')}};
 const searchAreaPlace=async()=>{if(!areaQuery.trim())return;setBusy(true);try{setAreaResults(await searchPlace(areaQuery));}catch{setMsg('Området kunde inte hittas.')}finally{setBusy(false)}};
 const chooseArea=async(r:GeocodingResult)=>{const next={name:r.displayName,latitude:r.latitude,longitude:r.longitude,radiusKm:areaRadius};await saveSearchArea(next);setArea(next);setAreaOpen(false);setAreaQuery('');setAreaResults([]);map.current?.animateToRegion({latitude:r.latitude,longitude:r.longitude,latitudeDelta:0.3,longitudeDelta:0.3},500);setMsg('Sökområdet sparades.');};
 const resetArea=async()=>{await clearSearchArea();setArea(null);setAreaOpen(false);setAreaResults([]);setMsg('Sökområdet rensades.');};
 return <View style={s.container}><MapView ref={map} style={StyleSheet.absoluteFill} mapType={sat?'satellite':'standard'} initialRegion={FALLBACK} toolbarEnabled onPress={e=>add(e.nativeEvent.coordinate)}>{points.map((p,i)=><Marker key={p.id} coordinate={p} title={`${i+1}. ${p.label}`}/>)}{points.length>1&&<Polyline coordinates={points} strokeWidth={4} strokeColor="#1769e0"/>}</MapView><SafeAreaView style={s.overlay}><View style={s.top}><View style={s.head}><View><Text style={s.title}>RouteMapper</Text><Text>{points.length} stopp</Text></View><Pressable style={s.areaButton} onPress={()=>setAreaOpen(true)}><Text style={s.areaButtonText}>{area?'Område valt':'Välj område'}</Text></Pressable></View>{area?<Text style={s.areaText} numberOfLines={1}>Söker inom {area.radiusKm} km från {area.name}</Text>:null}<ScrollView horizontal><View style={s.row}><Pressable style={s.btn} onPress={()=>setSearchOpen(true)}><Text>Adress</Text></Pressable><Pressable style={s.btn} onPress={importImage}><Text>📷 Bild</Text></Pressable><Pressable style={s.btn} onPress={()=>setSat(x=>!x)}><Text>{sat?'Karta':'Satellit'}</Text></Pressable><Pressable style={s.btn} onPress={street}><Text>Street View</Text></Pressable></View></ScrollView></View>{msg?<Pressable style={s.msg} onPress={()=>setMsg('')}><Text>{msg}</Text></Pressable>:null}<View style={[s.bottom,{paddingBottom:insets.bottom+8}]}><View style={s.row}><Pressable style={s.btn} onPress={async()=>{if(!points.length)return setMsg('Lägg till stopp först.');try{await shareRouteAsGpx(points,'RouteMapper route');setMsg('GPX klar.')}catch{setMsg('GPX misslyckades.')}}}><Text>GPX</Text></Pressable><Pressable style={s.primary} onPress={async()=>{if(!points.length)return setMsg('Lägg till stopp först.');const ok=await openRouteInOsmAnd(points);setMsg(ok?'Skickad till OsmAnd.':'Kunde inte öppna OsmAnd.')}}><Text style={s.white}>Navigera i OsmAnd</Text></Pressable></View></View></SafeAreaView>
 <Modal visible={searchOpen} transparent animationType="slide"><View style={s.back}><View style={s.modal}><Text style={s.title}>Sök adress</Text><View style={s.row}><TextInput style={s.input} value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Gata och nummer, ort"/><Pressable style={s.primary} onPress={search}><Text style={s.white}>{busy?'…':'Sök'}</Text></Pressable></View>{busy?<ActivityIndicator/>:null}{results.map(r=><Pressable key={`${r.latitude}-${r.longitude}`} style={s.result} onPress={()=>{add(r,r.displayName.split(',').slice(0,2).join(', '));setResults([]);setQuery('');setSearchOpen(false)}}><Text>{r.displayName}</Text></Pressable>)}<Pressable style={s.btn} onPress={()=>setSearchOpen(false)}><Text>Stäng</Text></Pressable></View></View></Modal>
 <Modal visible={areaOpen} transparent animationType="slide"><View style={s.back}><View style={s.modal}><Text style={s.title}>Sökområde</Text><Text style={s.description}>Välj en plats som centrum för adressökningen.</Text><View style={s.row}><TextInput style={s.input} value={areaQuery} onChangeText={setAreaQuery} onSubmitEditing={searchAreaPlace} placeholder="Sök plats"/><Pressable style={s.primary} onPress={searchAreaPlace}><Text style={s.white}>{busy?'…':'Sök'}</Text></Pressable></View>{areaResults.map(r=><Pressable key={`${r.latitude}-${r.longitude}`} style={s.result} onPress={()=>chooseArea(r)}><Text>{r.displayName}</Text></Pressable>)}<Text style={s.label}>Radie</Text><ScrollView horizontal><View style={s.row}>{RADII.map(r=><Pressable key={r} style={[s.radius,areaRadius===r&&s.radiusSelected]} onPress={()=>setAreaRadius(r)}><Text>{r} km</Text></Pressable>)}</View></ScrollView><View style={s.row}><Pressable style={s.btn} onPress={()=>setAreaOpen(false)}><Text>Stäng</Text></Pressable>{area?<Pressable style={s.delete} onPress={resetArea}><Text style={s.white}>Rensa område</Text></Pressable>:null}</View></View></View></Modal></View>}
const s=StyleSheet.create({container:{flex:1},overlay:{flex:1,justifyContent:'space-between'},top:{margin:12,padding:12,borderRadius:16,backgroundColor:'rgba(255,255,255,.94)',elevation:4},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:21,fontWeight:'700'},row:{flexDirection:'row',gap:8,alignItems:'center'},areaButton:{backgroundColor:'#1769e0',padding:10,borderRadius:10},areaButtonText:{color:'#fff',fontWeight:'700'},areaText:{marginTop:6,fontSize:12},btn:{backgroundColor:'#fff',padding:11,borderRadius:10,elevation:2},primary:{backgroundColor:'#1769e0',padding:11,borderRadius:10},delete:{backgroundColor:'#b42318',padding:11,borderRadius:10},white:{color:'#fff',fontWeight:'700'},bottom:{padding:12},msg:{alignSelf:'center',backgroundColor:'#fff',padding:12,borderRadius:12},back:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.35)'},modal:{backgroundColor:'#fff',padding:18,borderTopLeftRadius:20,borderTopRightRadius:20,gap:12},input:{flex:1,borderWidth:1,borderColor:'#ccc',borderRadius:10,padding:10},result:{padding:14,borderBottomWidth:1,borderBottomColor:'#eee'},description:{color:'#555'},label:{fontWeight:'700'},radius:{padding:10,borderRadius:10,backgroundColor:'#eee'},radiusSelected:{backgroundColor:'#d5e7ff'}});
